### PR TITLE
fix unexpected result

### LINKED ISSUE #18: [BUG] relation calculator 部分计算error
### Description / Steps to reproduce the issue

I discovered an unexpected result from the calculator:
1. 哥哥的母亲/父亲 shouldn't be 哥哥
2. 姐姐的母亲/父亲 shouldn't be 姐姐

### Issue Architecture

[Arch: arm]

### PR DESCRIPTION
**Pull request by jiayadong8995**
fix [issues](https://github.com/open-vela/packages_demos/issues/18)
Regarding the support of more relationships, I am thinking of using files.

### CODE REVIEW

File: relation_calculator/relation_cal.c [hunk 1]
```diff
@@ -32,7 +32,7 @@ static const relation_transformation_t transitions[] = {
     {REL_FATHER, REL_MOTHER, REL_GRANDMOTHER}, // Father's mother is grandmother
     {REL_MOTHER, REL_FATHER, REL_GRANDFATHER}, // Mother's father is grandfather
     {REL_MOTHER, REL_MOTHER, REL_GRANDMOTHER}, // Mother's mother is grandmother
-    {REL_GRANDFATHER, REL_SON, REL_UNCLE},     // Grandfather to son is REL_UNCLE
+    {REL_GRANDFATHER, REL_SON, REL_FATHER},     // Grandfather to son is REL_UNCLE
```
Comment (jianglianfang) [inline relation_calculator/relation_cal.c]: REL_FATHER as well

File: relation_calculator/relation_cal.c [hunk 2]
```diff
@@ -48,10 +48,10 @@ static const relation_transformation_t transitions[] = {
     {REL_MATERNAL_GRANDMOTHER, REL_MOTHER, REL_MATERNAL_GREAT_GRANDMOTHER}, // Maternal grandmother's mother is maternal great - grandmother
 
     // Sibling relationships
-    {REL_ELDER_BROTHER, REL_FATHER, REL_ELDER_BROTHER},              // Elder brother to father remains elder brother
-    {REL_ELDER_BROTHER, REL_MOTHER, REL_ELDER_BROTHER},              // Elder brother to mother remains elder brother
-    {REL_YOUNGER_BROTHER, REL_FATHER, REL_YOUNGER_BROTHER},          // Younger brother to father remains younger brother
-    {REL_YOUNGER_BROTHER, REL_MOTHER, REL_YOUNGER_BROTHER},          // Younger brother to mother remains younger brother
+    {REL_ELDER_BROTHER, REL_FATHER, REL_FATHER},             
+    {REL_ELDER_BROTHER, REL_MOTHER, REL_MOTHER},             
+    {REL_YOUNGER_BROTHER, REL_FATHER, REL_FATHER},          // Younger brother to father remains younger brother
```
Comment (jianglianfang) [inline relation_calculator/relation_cal.c]: remove it or change it to a right comment

File: relation_calculator/relation_cal.c (hunk 1 above)
Comment (jiayadong8995) [reply relation_calculator/relation_cal.c]: Due to algorithm defects, I can only choose REL_FATHER or REL_UNCLE，maybe I need to optimize my algorithm.

File: relation_calculator/relation_cal.c (hunk 2 above)
Comment (jiayadong8995) [reply relation_calculator/relation_cal.c]: I have changed it to a right comment.

File: relation_calculator/relation_cal.c (hunk 1 above)
Comment (jianglianfang) [reply relation_calculator/relation_cal.c]: comment should be changed to REL_FATHER as well

Comment (jiayadong8995) [reply relation_calculator/relation_cal.c]: I have fixed it and squashed my change into one patch

**Review by jianglianfang — APPROVED** [review]

**Review by W-Mai — APPROVED** [review]
